### ISSUE TITLE
grabber not fining qr code

### ISSUE THREAD

**Issue by herman-nietzen** [raptored01/whatsapp_hack#4]
(env) C:\Users\Admin\Desktop\whatsapp_hack>python grabber.py
Traceback (most recent call last):
  File "grabber.py", line 15, in <module>
    EC.presence_of_element_located((By.XPATH, """//*[@id="app"]/div/div/div[2]/div/div[2]/div/img""")))
  File "C:\Users\Admin\Desktop\whatsapp_hack\env\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

pls help
I tried it by manually scaping the png and starting the server, but it is changing quickly and I don't understand how the two files communicate, what is the output?

**Comment by herman-nietzen** [comment]
I do not understand what exactly happens in this line: 
    EC.presence_of_element_located((By.XPATH, """//*[@id="app"]/div/div/div[2]/div/div[2]/div/img""")))
Could you maybe elaborate or give me a hint whether it is to which router settings? I am new to this.

Thank you very much in advance! :)

**Comment by ak5617** [comment]
Hi sir
Grabber is not find qr code as usually I install all the requirements of it as geckodriver,webdriver etc please help and suggest me

**Comment by Venkateshrepala** [comment]
Traceback (most recent call last):
  File "grabber.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by mandiri1155** [comment]
![857413869_378238](https://user-images.githubusercontent.com/62487840/77934948-fc53aa80-72da-11ea-88c8-9f1b51992e7f.jpg)
Tolong bantuannya guru
